version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: colectivos-mongo
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: colectivos-db
    volumes:
      - mongodb_data:/data/db
    networks:
      - colectivos-network

volumes:
  mongodb_data:

networks:
  colectivos-network:
    driver: bridge
